import Stringable from './Stringable.js';
import strAfter from './strAfter.js';
import strAfterLast from './strAfterLast.js';
import strAppend from './strAppend.js';
import strBasename from './strBasename.js';
import strBefore from './strBefore.js';
import strBeforeLast from './strBeforeLast.js';
import strBetween from './strBetween.js';
import strCamel from './strCamel.js';
import strContains from './strContains.js';
import strContainsAll from './strContainsAll.js';
import strDirname from './strDirname.js';
import strEndsWith from './strEndsWith.js';
import strEscapeHtml from './strEscapeHtml.js';
import strEscapeHtmlComment from './strEscapeHtmlComment.js';
import strFinish from './strFinish.js';
import strIs from './strIs.js';
import strIsAscii from './strIsAscii.js';
import strIsUuid from './strIsUuid.js';
import strKebab from './strKebab.js';
import strLcfirst from './strLcfirst.js';
import strLimit from './strLimit.js';
import strLowerFirst from './strLowerFirst.js';
import strLtrim from './strLtrim.js';
import strPadBoth from './strPadBoth.js';
import strParseCallback from './strParseCallback.js';
import strPortion from './strPortion.js';
import strPrepend from './strPrepend.js';
import strRandom from './strRandom.js';
import strRemove from './strRemove.js';
import strReplaceArray from './strReplaceArray.js';
import strReplaceFirst from './strReplaceFirst.js';
import strReplaceLast from './strReplaceLast.js';
import strReplaceMany from './strReplaceMany.js';
import strRtrim from './strRtrim.js';
import strSanitize from './strSanitize.js';
import strSlug from './strSlug.js';
import strSnake from './strSnake.js';
import strStart from './strStart.js';
import strStartsWith from './strStartsWith.js';
import strStripHtml from './strStripHtml.js';
import strStudly from './strStudly.js';
import strSubstrCount from './strSubstrCount.js';
import strTitle from './strTitle.js';
import strTrim from './strTrim.js';
import strTrimEnd from './strTrimEnd.js';
import strTrimStart from './strTrimStart.js';
import strUcfirst from './strUcfirst.js';
import strUcwords from './strUcwords.js';
import strUpperFirst from './strUpperFirst.js';
import strUpperWords from './strUpperWords.js';
import strWhen from './strWhen.js';
import strWhenEmpty from './strWhenEmpty.js';
import strWords from './strWords.js';

function str(value = ''): Stringable {
    return new Stringable(value);
}

// str.of = (value: string = ''): Stringable => new Stringable(value);
str.after = strAfter;
str.afterLast = strAfterLast;
str.append = strAppend;
str.basename = strBasename;
str.before = strBefore;
str.beforeLast = strBeforeLast;
str.between = strBetween;
str.camel = strCamel;
str.contains = strContains;
str.containsAll = strContainsAll;
str.dirname = strDirname;
str.endsWith = strEndsWith;
str.escapeHtml = strEscapeHtml;
str.escapeHtmlComment = strEscapeHtmlComment;
str.finish = strFinish;
str.is = strIs;
str.isAscii = strIsAscii;
str.isUuid = strIsUuid;
str.kebab = strKebab;
str.lcfirst = strLcfirst;
str.limit = strLimit;
str.lowerFirst = strLowerFirst;
str.ltrim = strLtrim;
str.padBoth = strPadBoth;
str.parseCallback = strParseCallback;
str.portion = strPortion;
str.prepend = strPrepend;
str.random = strRandom;
str.remove = strRemove;
str.replaceArray = strReplaceArray;
str.replaceFirst = strReplaceFirst;
str.replaceLast = strReplaceLast;
str.replaceMany = strReplaceMany;
str.rtrim = strRtrim;
str.sanitize = strSanitize;
str.slug = strSlug;
str.snake = strSnake;
str.start = strStart;
str.startsWith = strStartsWith;
str.stripHtml = strStripHtml;
str.studly = strStudly;
str.substrCount = strSubstrCount;
str.title = strTitle;
str.trim = strTrim;
str.trimEnd = strTrimEnd;
str.trimStart = strTrimStart;
str.ucfirst = strUcfirst;
str.ucwords = strUcwords;
str.upperFirst = strUpperFirst;
str.upperWords = strUpperWords;
str.when = strWhen;
str.whenEmpty = strWhenEmpty;
str.words = strWords;

export default str;
