import Stringable from './Stringable';
import strAfter from './strAfter';
import strAfterLast from './strAfterLast';
import strAppend from './strAppend';
import strBasename from './strBasename';
import strBefore from './strBefore';
import strBeforeLast from './strBeforeLast';
import strBetween from './strBetween';
import strCamel from './strCamel';
import strContains from './strContains';
import strContainsAll from './strContainsAll';
import strDirname from './strDirname';
import strEndsWith from './strEndsWith';
import strEscapeHtml from './strEscapeHtml';
import strEscapeHtmlComment from './strEscapeHtmlComment';
import strFinish from './strFinish';
import strIs from './strIs';
import strIsAscii from './strIsAscii';
import strIsUuid from './strIsUuid';
import strKebab from './strKebab';
import strLcfirst from './strLcfirst';
import strLimit from './strLimit';
import strLowerFirst from './strLowerFirst';
import strLtrim from './strLtrim';
import strPadBoth from './strPadBoth';
import strParseCallback from './strParseCallback';
import strPortion from './strPortion';
import strPrepend from './strPrepend';
import strRandom from './strRandom';
import strRemove from './strRemove';
import strReplaceArray from './strReplaceArray';
import strReplaceFirst from './strReplaceFirst';
import strReplaceLast from './strReplaceLast';
import strReplaceMany from './strReplaceMany';
import strRtrim from './strRtrim';
import strSanitize from './strSanitize';
import strSlug from './strSlug';
import strSnake from './strSnake';
import strStart from './strStart';
import strStartsWith from './strStartsWith';
import strStripHtml from './strStripHtml';
import strStudly from './strStudly';
import strSubstrCount from './strSubstrCount';
import strTitle from './strTitle';
import strTrim from './strTrim';
import strTrimEnd from './strTrimEnd';
import strTrimStart from './strTrimStart';
import strUcfirst from './strUcfirst';
import strUcwords from './strUcwords';
import strUpperFirst from './strUpperFirst';
import strUpperWords from './strUpperWords';
import strWhen from './strWhen';
import strWhenEmpty from './strWhenEmpty';
import strWords from './strWords';

function str(value = ''): Stringable {
    return new Stringable(value);
}

// str.of = (value: string = ''): Stringable => new Stringable(value);
str.after = strAfter;
str.afterLast = strAfterLast;
str.append = strAppend;
str.basename = strBasename;
str.before = strBefore;
str.beforeLast = strBeforeLast;
str.between = strBetween;
str.camel = strCamel;
str.contains = strContains;
str.containsAll = strContainsAll;
str.dirname = strDirname;
str.endsWith = strEndsWith;
str.escapeHtml = strEscapeHtml;
str.escapeHtmlComment = strEscapeHtmlComment;
str.finish = strFinish;
str.is = strIs;
str.isAscii = strIsAscii;
str.isUuid = strIsUuid;
str.kebab = strKebab;
str.lcfirst = strLcfirst;
str.limit = strLimit;
str.lowerFirst = strLowerFirst;
str.ltrim = strLtrim;
str.padBoth = strPadBoth;
str.parseCallback = strParseCallback;
str.portion = strPortion;
str.prepend = strPrepend;
str.random = strRandom;
str.remove = strRemove;
str.replaceArray = strReplaceArray;
str.replaceFirst = strReplaceFirst;
str.replaceLast = strReplaceLast;
str.replaceMany = strReplaceMany;
str.rtrim = strRtrim;
str.sanitize = strSanitize;
str.slug = strSlug;
str.snake = strSnake;
str.start = strStart;
str.startsWith = strStartsWith;
str.stripHtml = strStripHtml;
str.studly = strStudly;
str.substrCount = strSubstrCount;
str.title = strTitle;
str.trim = strTrim;
str.trimEnd = strTrimEnd;
str.trimStart = strTrimStart;
str.ucfirst = strUcfirst;
str.ucwords = strUcwords;
str.upperFirst = strUpperFirst;
str.upperWords = strUpperWords;
str.when = strWhen;
str.whenEmpty = strWhenEmpty;
str.words = strWords;

export default str;
